
# ==========================================
# 2. THE ORDER CONVERTER (The Math Engine)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-generator
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: order-generator
  template:
    metadata:
      labels:
        app: order-generator
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "5000" 
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: generator
        image: vivek22v/ecommerce-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["python", "order_gen.py"]
        envFrom:
        - configMapRef:
            name: ecommerce-config
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:            
            cpu: "500m"      
            memory: "512Mi"  

---
# ==========================================
# 3. THE DELIVERY FULFILLER (Logistics)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-generator
  template:
    metadata:
      labels:
        app: delivery-generator
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "5000"     
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: generator
        image: vivek22v/ecommerce-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["python", "delivery_gen.py"]
        envFrom:
        - configMapRef:
            name: ecommerce-config
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---