# ==========================================
# 1. THE ORDER GENERATOR (Financials)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-generator
  template:
    metadata:
      labels:
        app: order-generator
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "5000"   
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: generator
        image: vivek22v/ecommerce-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["python", "order_gen.py"]
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: KAFKA_ORDER_TOPIC
          value: "ecommerce_orders"
        - name: SLEEP_MIN
          value: "0.5"
        - name: SLEEP_MAX
          value: "2.0"

---
# ==========================================
# 2. THE CLICKSTREAM GENERATOR (Web Traffic)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickstream-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickstream-generator
  template:
    metadata:
      labels:
        app: clickstream-generator
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "5000" 
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: generator
        image: vivek22v/ecommerce-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["python", "clickstream_gen.py"]
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: KAFKA_CLICKSTREAM_TOPIC
          value: "ecommerce_clickstream"
        - name: SLEEP_MIN
          value: "0.1"
        - name: SLEEP_MAX
          value: "0.5"

---
# ==========================================
# 3. THE INVENTORY GENERATOR (Warehouse)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-generator
  template:
    metadata:
      labels:
        app: inventory-generator
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "5000"     
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: generator
        image: vivek22v/ecommerce-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["python", "inventory_gen.py"]
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: KAFKA_INVENTORY_TOPIC
          value: "ecommerce_inventory"
        - name: SLEEP_MIN
          value: "0.5"
        - name: SLEEP_MAX
          value: "1.5"

---
# ==========================================
# 4. THE DATA PROCESSOR (The Brain)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
      annotations:                     
        prometheus.io/scrape: "true"   
        prometheus.io/port: "4040"     
        prometheus.io/path: "/metrics/prometheus"
    spec:
      containers:
      - name: processor
        image: vivek22v/ecommerce-processor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4040 
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: DB_PASSWORD
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: AWS_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ecommerce-secrets
                key: AWS_SECRET_KEY