apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  DB_HOST: "ecommerce-secure-db.ce7q08uos99n.us-east-1.rds.amazonaws.com"
  DB_NAME: "ecommerce_db"
  DB_USER: "dbadmin"
  S3_BUCKET: "ecommerce-datalake-9e127dc9"
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_TOPIC: "ecommerce_orders"
