apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ecommerce-generators-monitor
  namespace: monitoring      # Must be in the same namespace as Prometheus
  labels:
    release: kube-mon        # 👈 CRITICAL: This must match your Helm install name
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [order-generator, clickstream-generator, inventory-generator]}
  podMetricsEndpoints:
  - port: metrics            # This matches the port name in your apps.yaml
    path: /metrics
    interval: 15s