name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Generators Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/generator
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-generator:latest

    - name: Build and Push Processor Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/processor
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-processor:latest

    - name: Build and Push Dashboard Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/dashboard
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-dashboard:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update KubeConfig
      run: aws eks update-kubeconfig --region us-east-1 --name ecommerce-cluster

    - name: Deploy to EKS & Enable Cluster Autoscaler
      run: |
        kubectl apply -f k8s/apps.yaml
        kubectl apply -f k8s/dashboard.yaml
        
        curl -sL https://raw.githubusercontent.com/kubernetes/autoscaler/master/cluster-autoscaler/cloudprovider/aws/examples/cluster-autoscaler-autodiscover.yaml -o autoscaler.yaml
        
        sed -i 's/<YOUR CLUSTER NAME>/ecommerce-cluster/g' autoscaler.yaml
      
        kubectl apply -f autoscaler.yaml

        kubectl rollout restart deployment cart-generator order-generator delivery-generator ecommerce-processor ecommerce-dashboard